### ISSUE TITLE
Video recordings missing

### ISSUE THREAD

**Issue by OxanaHart** [James-Thorson/2018_FSH556#24]
Hello James,
I have been following the videos of your lectures and they have just gone missing from the Google drive. Could you please reupload them?
Thank you
Oxana

**Comment by James-Thorson** [comment]
They're all on YouTube FishStats ... Do you mind looking there instead?

**Comment by agruss2** [comment]
@OxanaHart Here are the Youtube videos that Jim mentioned: https://www.youtube.com/@fishstats5375/videos. You can close the GitHub issue as it has been resolved. Enjoy going over the class materials, this is an awesome course :) 
@James-Thorson Oxana is a Victoria University of Wellington (VUW) Masters student. She is currently taking classes, including one where she is going over the 2018_FSH556 materials. She will start her Masters project on 8th July 2024. Her Masters project will consist of developing VAST models to investigate stock structure, seasonality and environmental influences in the SNA8 and SNA7 snapper (Chrysophrys auratus) stocks. I am sure you both would love to exchange a few thoughts about this project and follow up with an email? :)
@James-Thorson (2) It would be a good idea to update the README to indicate that the videos are available on Youtube, since the recordings are not available in Google Drive anymore.

**Comment by OxanaHart** [comment]
Thank you!
Sorry, I did not realise that there is a YouTube channel.
